#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01)
# shellcheck disable=SC2086
get_info () {

    
    if [ $# -eq 1 ]; then
        subdomain="www.$1 lb-01.$1 web-01.$1 web-02.$1"
    elif [ $# -eq 2 ]; then
        subdomain="$2.$1"
    fi
    if [ $# -eq 0 ]; then
        dig $subdomain | awk '/ANSWER SECTION:/ { getline; split($1, a, "."); print "The subdomain", a[1], "is a", "$4", "record and points to", "$5"}'
    fi
    exit 0
}
get_info "$1" "$2"
