#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01). Let’s also add other subdomains to make our life easier, and write a Bash script that will display information about subdomains.
# shellcheck disable=SC2086

get_info () {

    dominio="$1"
    
    #verifico si pasaron un subdomain
    if [ "$2" ]
    then
        # si es ais lo seteamos
	    subdomain="$2"
    else
        # sino asigno el valor
	    subdomain="www lb-01 web-01 web-02"
    fi
    # recorremos cada subdomain
    for sub in $subdomain
    do
	    echo -n "The subdomain $sub"
	    # con dig saco toda la info de ese dns y la organizo con tail y awk
        dig $sub.$dominio | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print " is a " $4 " record and points to " $5}'
    done
}

get_info "$1" "$2"
