#!/usr/bin/env bash
# script Bash que transfiera un archivo de nuestro cliente a un servidor

if [ $# -eq 4 ]
then
	scp -o StrictHostKeyChecking=no -i "$1" "$3"@"$2":~/
else
	echo -e "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
