#!/usr/bin/env bash
# redirect 301 rewritedirectiva establece una redirección temporal
sudo sed -i '18 a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx restart
