#!/usr/bin/env bash
# redirect 301 rewritedirectiva establece una redirección temporal
sudo apt-get update
sudo apt-get install nginx -y
echo 'Holberton School' | sudo tee /var/www/html/index.html
sudo sed -i '18 a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx restart
