#!/usr/bin/env bash
# install nginx  and do a get request
sudo apt-get update
sudo apt-get install nginx -y
header_http="\n\add_header X-Served-By '$HOSTNAME'"
sudo sed -i "59i\ $header_http" /etc/nginx/sites-available/default
sudo service nginx restart
sudo nginx -t
